### ISSUE TITLE
Convert bookmarklet to Chrome extension

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/version-tracking-ui#3]
Might be nice to have this as an extension instead of bookmarklet. Could automatically run it on any site page, OR just click a button to generate a full report on any of the 150 domains, or on a subset of domains, and display that in a table which could be exported as CSV.  

Would need to be sure to avoid rapidly repeated requests to avoid violating TOS.

**Comment by dcwalk** [comment]
I'm going to close this out as development on the Web Monitoring project has moved on (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
