### ISSUE TITLE
include source code of bookmarklet

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/version-tracking-ui#7]
will be useful if we want to make changes later on & @jpmckinney isn't available. Also if e.g. @geppy wants to make a chrome extension.

**Comment by jpmckinney** [comment]
It's already in https://github.com/edgi-govdata-archiving/version-tracking-ui/blob/gh-pages/browser-tool.js

**Comment by jpmckinney** [comment]
Or, rather, you can go to https://edgi-govdata-archiving.github.io/version-tracking-ui/ and copy the bookmarklet.

**Comment by titaniumbones** [comment]
I just thought it might be nice to have as a separate file. Maybe I'm
being silly. I guess is beter to hack in place & use the gh-pages
generated site to test changes.

**Comment by jpmckinney** [comment]
It becomes a maintenance issue: the code should only be in one place, otherwise we have to carefully keep it in sync. Someone could probably rig up a `npm run build` that merges the code from a separate file, but seems unnecessary.

**Comment by titaniumbones** [comment]
Agreed, documenting source instead, as you've done, seems better. 

On January 27, 2017 12:00:11 AM EST, James McKinney <notifications@github.com> wrote:
>It becomes a maintenance issue: the code should only be in one place,
>otherwise we have to carefully keep it in sync. Someone could probably
>rig up a `npm run build` that merges the code from a separate file, but
>seems unnecessary.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/version-tracking-ui/issues/7#issuecomment-275589449

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
