### ISSUE TITLE
Find or develop an html diffing tool in js

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/version-tracking-ui#9]
[jsdifflib-node](https://github.com/marcosc90/node-jsdifflib) seems to be relatively actively maintained, but is, obviously, designed for node; [here's the parent library, difflibjs](https://github.com/cemerick/jsdifflib), which seems to have some outstanding bugs.  

Depends on #3.

**Comment by jpmckinney** [comment]
How would this fit into existing workflows? I don't think we want to rebuild Versionista, right?

**Comment by titaniumbones** [comment]
It looks like it would be a great help to be able to filter out some
diffs that are repeated many times over (mostly header & footer).  In
order to do that ,we would need to read & diff the files somehow. 
Obviously this requires an extension first.

**Comment by jpmckinney** [comment]
In that case, we're just using Versionista to collect versions, and then performing all the diffing ourselves?

**Comment by titaniumbones** [comment]
well, sorta.  We would need to perform the diff, see if it passes a
test, and if not mark it as irrelevant.  We could sitll use the
versionista UI for viewing diffs, we'd just perform an initial
low-bar-of-acceptance filter against known trivial changes. It's a
dramatic expansion of the tool, I guess -- but eventually we're going to
need it, I guess the monitoring team is finding it a full-time job for
about 5 people already.

**Comment by dcwalk** [comment]
This is happening (so exciting!) in a few different repos, see https://github.com/edgi-govdata-archiving/web-monitoring for progress. Closing as appropriate issues are ticketed there
